<!DOCTYPE html>
<html lang="en"><head>
<script src="iot_files/libs/clipboard/clipboard.min.js"></script>
<script src="iot_files/libs/quarto-html/tabby.min.js"></script>
<script src="iot_files/libs/quarto-html/popper.min.js"></script>
<script src="iot_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="iot_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="iot_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="iot_files/libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.31">

  <title>Tuna Canning at IOT</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="iot_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="iot_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="iot_files/libs/revealjs/dist/theme/quarto-1269d9ef3e09b27ec87013c1f4935fc6.css">
  <link href="iot_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="iot_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="iot_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="iot_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="iot_files/libs/quarto-diagram/mermaid.min.js"></script>
  <script src="iot_files/libs/quarto-diagram/mermaid-init.js"></script>
  <link href="iot_files/libs/quarto-diagram/mermaid.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Tuna Canning at IOT</h1>
  <p class="subtitle">Indian Ocean Tuna Ltd, Victoria, Seychelles</p>

<div class="quarto-title-authors">
</div>

</section>
<section class="slide level2">

<style>
.reveal pre {
    width: 98%;
    margin: auto;
    font-size: 0.7em;
    line-height: 1.1;
}
.reveal code {
    max-width: none;
    overflow-x: auto;
}
.reveal table {
    font-size: 0.75em;
    margin: auto;
    width: 95%;
}
</style>
</section>
<section class="slide level2">

</section>
<section>
<section id="section" class="title-slide slide level1 center" data-background-image="cover.png ">
<h1></h1>

</section>
<section class="slide level2">

</section></section>
<section>
<section id="tuna-canning-at-iot" class="title-slide slide level1 center">
<h1>Tuna Canning at IOT</h1>

</section>
<section id="indian-ocean-tuna-ltd-victoria-seychelles" class="slide level2">
<h2>Indian Ocean Tuna Ltd, Victoria, Seychelles</h2>
</section>
<section id="overview" class="slide level2">
<h2>Overview</h2>
<ul>
<li><strong>Location:</strong> Victoria, Seychelles</li>
<li><strong>Capacity:</strong> 335 tons/day round fish processing</li>
<li><strong>Production:</strong> 1.5-2 million cans per day</li>
<li><strong>Cold Storage:</strong> 12,000 tons capacity</li>
<li><strong>Employment:</strong> 1,800 workers (largest private employer)</li>
<li><strong>Export Markets:</strong> 95% to EU (France, Italy, UK)</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Thai Union’s 3rd largest factory globally - Two distinct processing streams</p>
</div>
</div>
</div>
</section>
<section id="processing-routes" class="slide level2">
<h2>Processing Routes</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="raw-pack-rp">Raw Pack (RP)</h3>
<ul>
<li>Large tuna (big size fish)</li>
<li>Raw filling directly into cans</li>
<li>Single cooking step (in-can only)</li>
<li><strong>Recovery: 62%</strong></li>
<li>Juicier texture, natural oils</li>
<li>Faster processing</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="pre-cook-pc">Pre-Cook (PC)</h3>
<ul>
<li>Smaller tuna</li>
<li>Pre-cooked then filled</li>
<li>Double cooking process</li>
<li><strong>Recovery: 45%</strong></li>
<li>Cleaner taste</li>
<li>Premium portion control</li>
</ul>
</div></div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>Recovery rate difference: 17 percentage points (38% more yield for raw pack!)</p>
</div>
</div>
</div>
</section>
<section id="step-1-cold-storage" class="slide level2">
<h2>Step 1: Cold Storage</h2>
<h3 id="three-storage-facilities">Three Storage Facilities</h3>
<table class="caption-top">
<thead>
<tr class="header">
<th>Location</th>
<th>Type</th>
<th>Capacity</th>
<th>Shifts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>IOT Main</td>
<td>Frozen raw tuna</td>
<td>5,000 tons</td>
<td>3</td>
</tr>
<tr class="even">
<td>CCCS</td>
<td>Frozen raw tuna</td>
<td>4,500 tons</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Containers</td>
<td>Frozen raw tuna</td>
<td>2,500 tons</td>
<td>1</td>
</tr>
</tbody>
</table>
<p><strong>Total capacity:</strong> 12,000 tons</p>
<ul>
<li>Tuna arrives frozen from Port Victoria</li>
<li>Maintained at optimal temperature</li>
<li>Species: Yellowfin and Skipjack</li>
</ul>
</section>
<section id="step-2-sizing-sorting" class="slide level2">
<h2>Step 2: Sizing &amp; Sorting</h2>
<h3 id="three-sorting-lines">Three Sorting Lines</h3>
<table class="caption-top">
<thead>
<tr class="header">
<th>Line</th>
<th>Workers</th>
<th>Shifts</th>
<th>Capacity (tons/day)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Table 1</td>
<td>8 sorters</td>
<td>3</td>
<td>1,958</td>
</tr>
<tr class="even">
<td>Table 2</td>
<td>7 sorters</td>
<td>2</td>
<td>1,142</td>
</tr>
<tr class="odd">
<td>CCCS</td>
<td>18 sorters</td>
<td>1</td>
<td>979</td>
</tr>
</tbody>
</table>
<p><strong>Total capacity:</strong> 4,080 tons/day<br>
<strong>Efficiency:</strong> 85%</p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Size determines processing route: Large fish → RP, Smaller fish → PC</p>
</div>
</div>
</div>
</section>
<section id="raw-pack-process-overview" class="slide level2">
<h2>Raw Pack Process: Overview</h2>
<h3 id="complete-flow-7-steps">Complete Flow (7 Steps)</h3>
<ol type="1">
<li>Thawing in temperature-controlled tanks</li>
<li>Sizing/cutting raw fish</li>
<li>Raw filling directly into cans</li>
<li>Adding liquid (oil/brine/water)</li>
<li>Seaming for hermetic seal</li>
<li>Retort sterilization (cooking in-can)</li>
<li>Cooling, labeling, packing</li>
</ol>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Fish cooks in its own juices during sterilization - preserves natural flavor</p>
</div>
</div>
</div>
</section>
<section id="rp-step-3-thawing" class="slide level2">
<h2>RP Step 3: Thawing</h2>
<h3 id="thawing-specifications">Thawing Specifications</h3>
<ul>
<li><strong>160 tanks</strong> with 204 scows per bay</li>
<li>Average weight per scow: 0.70 kg</li>
<li><strong>Thaw time:</strong> 14 hours</li>
<li><strong>Efficiency:</strong> 85%</li>
<li><strong>Daily capacity:</strong> 163.2 tons</li>
</ul>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>⚠️ CRITICAL BOTTLENECK for Raw Pack production!</p>
</div>
</div>
</div>
</section>
<section id="rp-step-9-raw-pack-canning" class="slide level2">
<h2>RP Step 9: Raw Pack Canning</h2>
<h3 id="filling-equipment">Filling Equipment</h3>
<ul>
<li><strong>Marleen pump fillers</strong></li>
<li><strong>CFT seamers</strong></li>
<li>Operating hours: 20 hours/day</li>
<li>Efficiency: 75%</li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 16%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th>Can Size</th>
<th>Speed (cans/min)</th>
<th>Daily Production</th>
<th>Fill Weight</th>
<th>Round Fish Needed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>80g</td>
<td>300</td>
<td>270,000</td>
<td>0.06 kg</td>
<td>27.4 tons</td>
</tr>
<tr class="even">
<td>132g</td>
<td>350</td>
<td>315,000</td>
<td>0.10 kg</td>
<td>52.8 tons</td>
</tr>
<tr class="odd">
<td>160g</td>
<td>350</td>
<td>315,000</td>
<td>0.13 kg</td>
<td>63.5 tons</td>
</tr>
<tr class="even">
<td>190g</td>
<td>350</td>
<td>315,000</td>
<td>0.16 kg</td>
<td>83.3 tons</td>
</tr>
<tr class="odd">
<td>265g</td>
<td>250</td>
<td>225,000</td>
<td>0.21 kg</td>
<td>74.8 tons</td>
</tr>
<tr class="even">
<td>400g</td>
<td>200</td>
<td>180,000</td>
<td>0.32 kg</td>
<td>91.7 tons</td>
</tr>
</tbody>
</table>
</section>
<section id="raw-pack-pros-cons" class="slide level2">
<h2>Raw Pack: Pros &amp; Cons</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="advantages">✅ Advantages</h3>
<ul>
<li><strong>62% recovery rate</strong> (highest yield)</li>
<li><strong>Natural flavor</strong> preserved</li>
<li><strong>Juicier texture</strong></li>
<li><strong>Faster processing</strong> (fewer steps)</li>
<li><strong>Lower labor costs</strong></li>
<li>Retains fish oils naturally</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="considerations">⚠️ Considerations</h3>
<ul>
<li>More liquid exudate in can</li>
<li>Stronger flavor profile</li>
<li>Less uniform portions</li>
<li><strong>Bottleneck:</strong> Limited by thawing capacity (163 tons/day)</li>
</ul>
</div></div>
</section>
<section id="pre-cook-process-overview" class="slide level2">
<h2>Pre-Cook Process: Overview</h2>
<h3 id="complete-flow-10-steps">Complete Flow (10 Steps)</h3>
<ol type="1">
<li>Sizing (no thawing - frozen fish used)</li>
<li><strong>Racking</strong> - 245 kg per rack</li>
<li><strong>Pre-cooking</strong> in steam cookers</li>
<li><strong>Extractor cooling</strong></li>
<li><strong>Further cooling</strong> chambers</li>
<li><strong>Cleaning</strong> - manual removal of skin/bones</li>
<li>Filling cooked meat into cans</li>
<li>Adding liquid medium</li>
<li>Seaming</li>
<li>Final retort sterilization</li>
</ol>
</section>
<section id="pc-step-4-racking" class="slide level2">
<h2>PC Step 4: Racking</h2>
<h3 id="manual-racking-process">Manual Racking Process</h3>
<ul>
<li>Weight per rack: <strong>245 kg/rack</strong></li>
<li><strong>8 racker workers</strong>, 3 shifts</li>
<li>Target: 7 racks per hour per worker</li>
<li><strong>Efficiency:</strong> 85%</li>
<li><strong>Daily capacity:</strong> 251.9 tons</li>
</ul>
<p>Fish loaded onto metal racks for steam pressure cooking</p>
</section>
<section id="pc-step-5-pre-cooking" class="slide level2">
<h2>PC Step 5: Pre-Cooking</h2>
<h3 id="seven-steam-pressure-cookers">Seven Steam Pressure Cookers</h3>
<table class="caption-top">
<colgroup>
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 17%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Cooker</th>
<th>Racks</th>
<th>Kg/Rack</th>
<th>Cook Time</th>
<th>Cooks/Day</th>
<th>Efficiency</th>
<th>Tons/Day</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1-7</td>
<td>34</td>
<td>245</td>
<td>4 hours</td>
<td>6</td>
<td>90%</td>
<td>44.98 each</td>
</tr>
</tbody>
</table>
<p><strong>Total capacity:</strong> 314.9 tons/day</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Pre-cooking removes excess oils and prepares fish for easy skin/bone removal</p>
</div>
</div>
</div>
</section>
<section id="pc-step-6-7-cooling" class="slide level2">
<h2>PC Step 6 &amp; 7: Cooling</h2>
<h3 id="two-stage-cooling-process">Two-Stage Cooling Process</h3>
<p><strong>Extractor Chambers (Air flow cooling)</strong> - 4 chambers: 32-38 racks each - Holding time: 2 hours - Capacity: 429.2 tons/day</p>
<p><strong>Cooling Chambers (Extended cooling)</strong> - 4 chambers: 36-64 racks each<br>
- Holding time: 3 hours - Capacity: 446.9 tons/day</p>
</section>
<section id="pc-step-8-cleaning" class="slide level2">
<h2>PC Step 8: Cleaning</h2>
<h3 id="nine-cleaning-tables---most-labor-intensive-step">Nine Cleaning Tables - Most Labor Intensive Step</h3>
<table class="caption-top">
<thead>
<tr class="header">
<th>Table</th>
<th>Operators</th>
<th>Kg/Cleaner/Hr</th>
<th>Hours/Day</th>
<th>Capacity (tons/day)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tables 1-7</td>
<td>26 each</td>
<td>53</td>
<td>21</td>
<td>28.9 each</td>
</tr>
<tr class="even">
<td>Table 8</td>
<td>18</td>
<td>53</td>
<td>21</td>
<td>20.0</td>
</tr>
<tr class="odd">
<td>Table 9</td>
<td>25</td>
<td>53</td>
<td>21</td>
<td>27.8</td>
</tr>
</tbody>
</table>
<p><strong>Total capacity:</strong> 251.4 tons/day<br>
<strong>Total workers:</strong> ~200 people</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>⚠️ CRITICAL BOTTLENECK for Pre-Cook production!</p>
</div>
</div>
</div>
</section>
<section id="pc-step-10-pre-cook-canning" class="slide level2">
<h2>PC Step 10: Pre-Cook Canning</h2>
<h3 id="nine-production-lines">Nine Production Lines</h3>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 8%">
<col style="width: 19%">
<col style="width: 25%">
<col style="width: 16%">
<col style="width: 13%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Line</th>
<th>Product Type</th>
<th>Speed (cans/min)</th>
<th>Daily Cans</th>
<th>Recovery</th>
<th>Round Fish</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Chunk oil</td>
<td>500</td>
<td>450,000</td>
<td>45%</td>
<td>20 tons</td>
</tr>
<tr class="even">
<td>1</td>
<td>Chunk water</td>
<td>400</td>
<td>360,000</td>
<td>45%</td>
<td>16 tons</td>
</tr>
<tr class="odd">
<td>2-7</td>
<td>Chunk oil</td>
<td>200</td>
<td>180,000</td>
<td>45%</td>
<td>15.8 tons</td>
</tr>
<tr class="even">
<td>2-7</td>
<td>Steak water</td>
<td>180</td>
<td>162,000</td>
<td>45%</td>
<td>14.3 tons</td>
</tr>
<tr class="odd">
<td>9</td>
<td>Steak oil</td>
<td>190</td>
<td>171,000</td>
<td>45%</td>
<td>16.5 tons</td>
</tr>
</tbody>
</table>
<p>Products: Chunk, Flakes, Steak (in oil, water, or brine)<br>
Can size: Typically 170-210g</p>
</section>
<section id="pre-cook-pros-cons" class="slide level2">
<h2>Pre-Cook: Pros &amp; Cons</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="advantages-1">✅ Advantages</h3>
<ul>
<li><strong>Cleaner taste</strong> (less strong flavor)</li>
<li><strong>Precise portion control</strong></li>
<li><strong>Premium appearance</strong></li>
<li><strong>Better for chunk/flake products</strong></li>
<li>Easier to remove all bones/skin</li>
<li>More uniform product</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="considerations-1">⚠️ Considerations</h3>
<ul>
<li><strong>45% recovery</strong> (17% less than RP)</li>
<li>More labor intensive (~200 cleaners)</li>
<li>Higher processing costs</li>
<li>Longer processing time</li>
<li>Must add oils back</li>
<li><strong>Bottleneck:</strong> Cleaning tables limit to 251 tons/day</li>
</ul>
</div></div>
</section>
<section id="step-11-sterilization-retort" class="slide level2">
<h2>Step 11: Sterilization (Retort)</h2>
<h3 id="critical-food-safety-step">Critical Food Safety Step</h3>
<table class="caption-top">
<thead>
<tr class="header">
<th>Product</th>
<th>Can Size</th>
<th>Temp</th>
<th>Time</th>
<th>Cans/Basket</th>
<th>Cooks/Day</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>160g RP</td>
<td>1/5</td>
<td>121°C</td>
<td>41 min</td>
<td>1,200</td>
<td>6</td>
</tr>
<tr class="even">
<td>190g RP</td>
<td>1/4</td>
<td>121°C</td>
<td>48 min</td>
<td>1,000</td>
<td>6</td>
</tr>
<tr class="odd">
<td>265g RP</td>
<td>1/3</td>
<td>121°C</td>
<td>55 min</td>
<td>600</td>
<td>6</td>
</tr>
<tr class="even">
<td>400g RP</td>
<td>1/2</td>
<td>121°C</td>
<td>80 min</td>
<td>400</td>
<td>6</td>
</tr>
<tr class="odd">
<td>170g PC</td>
<td>1/4</td>
<td>117°C</td>
<td>65 min</td>
<td>1,000</td>
<td>6</td>
</tr>
<tr class="even">
<td>210g PC</td>
<td>1/3</td>
<td>117°C</td>
<td>72 min</td>
<td>600</td>
<td>6</td>
</tr>
</tbody>
</table>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Eliminates <em>Clostridium botulinum</em> and ensures shelf stability. Note: PC uses lower temp (117°C) vs RP (121°C)</p>
</div>
</div>
</div>
</section>
<section id="step-12-labeling-packaging" class="slide level2">
<h2>Step 12: Labeling &amp; Packaging</h2>
<h3 id="ten-packaging-lines-83-efficiency">Ten Packaging Lines (83% efficiency)</h3>
<p><strong>Line Types:</strong></p>
<ul>
<li><strong>Lines 1, 2A/2B:</strong> Clustering, shrinking, stickering</li>
<li><strong>Line 3:</strong> Manual and automated processes (traying, hood, casing)</li>
<li><strong>Lines 4-9:</strong> Specialized multi-pack configurations</li>
<li><strong>Line 10:</strong> Bulk packing (9,600 cans/pallet)</li>
</ul>
<p><strong>Pack configurations:</strong> 2-48 cans per carton<br>
<strong>Daily capacity:</strong> Varies by line and product (400-850 cases/hour)</p>
</section>
<section id="labeling-examples" class="slide level2">
<h2>Labeling Examples</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Line</th>
<th>Product</th>
<th>Process</th>
<th>Cases/Hour</th>
<th>Cases/Day</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>80g x2</td>
<td>Clustering + shrinking</td>
<td>400</td>
<td>5,976</td>
</tr>
<tr class="even">
<td>3</td>
<td>132g x24</td>
<td>Traying + shrinking</td>
<td>600</td>
<td>8,964</td>
</tr>
<tr class="odd">
<td>6</td>
<td>145g x48</td>
<td>Auto-cartoning</td>
<td>357</td>
<td>5,333</td>
</tr>
<tr class="even">
<td>8</td>
<td>265g x24</td>
<td>Traying + shrinking</td>
<td>765</td>
<td>11,429</td>
</tr>
</tbody>
</table>
<p>Processes include: sleeving, capping, traying, shrink-wrapping, cartoning, and stickering</p>
</section>
<section id="step-13-containerization" class="slide level2">
<h2>Step 13: Containerization</h2>
<h3 id="export-preparation">Export Preparation</h3>
<p><strong>Most Common Container Loads:</strong></p>
<ul>
<li>160g x48: 19.78% of containers (2,160 cases/container)</li>
<li>132g x48: 11.74% of containers (2,688 cases/container)</li>
<li>80g x96: 7.00% of containers (2,400 cases/container)</li>
</ul>
<p><strong>Destinations:</strong></p>
<ul>
<li>France (Petit Navire)</li>
<li>UK (John West)</li>
<li>Italy (Mareblu)</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Temperature-controlled containers ensure quality during shipping</p>
</div>
</div>
</div>
</section>
<section id="equipment-fillers-seamers" class="slide level2">
<h2>Equipment: Fillers &amp; Seamers</h2>
<h3 id="raw-pack-line">Raw Pack Line</h3>
<ul>
<li><strong>Marleen pump fillers</strong> handle raw fish pieces</li>
<li>Filling rate: 200-350 cans/min</li>
<li>Seaming occurs <strong>before cooking</strong></li>
<li>Equipment tolerates raw product variations</li>
<li>Fill weights: 0.06-0.32 kg per can</li>
</ul>
<h3 id="pre-cook-line">Pre-Cook Line</h3>
<ul>
<li>Multiple filler systems across 9 lines</li>
<li>Filling rate: 180-500 cans/min (Line 1 fastest)</li>
<li>Seaming occurs <strong>after filling cooked meat</strong></li>
<li>Greater precision and consistency</li>
<li>Fill weights: 0.05-0.10 kg per can</li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Seamer function identical in both—creating hermetic vacuum seals</p>
</div>
</div>
</div>
</section>
<section id="comparison-rp-vs-pc" class="slide level2">
<h2>Comparison: RP vs PC</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Factor</th>
<th>Raw Pack (RP)</th>
<th>Pre-Cook (PC)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Fish Size</strong></td>
<td>Large tuna (big size)</td>
<td>Smaller tuna</td>
</tr>
<tr class="even">
<td><strong>Cooking Steps</strong></td>
<td>1 (in-can only)</td>
<td>2 (pre-cook + retort)</td>
</tr>
<tr class="odd">
<td><strong>Recovery</strong></td>
<td>62%</td>
<td>45%</td>
</tr>
<tr class="even">
<td><strong>Texture</strong></td>
<td>Juicier, firmer</td>
<td>Tender, flaky</td>
</tr>
<tr class="odd">
<td><strong>Flavor</strong></td>
<td>Stronger, natural</td>
<td>Milder, cleaner</td>
</tr>
<tr class="even">
<td><strong>Labor</strong></td>
<td>Lower</td>
<td>Higher (200+ cleaners)</td>
</tr>
<tr class="odd">
<td><strong>Speed</strong></td>
<td>200-350 cpm</td>
<td>180-500 cpm</td>
</tr>
<tr class="even">
<td><strong>Processing Time</strong></td>
<td>6-7 steps</td>
<td>10 steps</td>
</tr>
<tr class="odd">
<td><strong>Bottleneck</strong></td>
<td>Thawing (163 t/d)</td>
<td>Cleaning (251 t/d)</td>
</tr>
<tr class="even">
<td><strong>Product Type</strong></td>
<td>Various sizes</td>
<td>Chunk/Flake/Steak</td>
</tr>
</tbody>
</table>
</section>
<section id="bottleneck-analysis" class="slide level2">
<h2>Bottleneck Analysis</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="raw-pack-chain">Raw Pack Chain</h3>
<ol type="1">
<li>Sorting: 4,080 t/d ✓</li>
<li><strong>Thawing: 163 t/d</strong> ⚠️</li>
<li>Filling: ~92 t/d ✓</li>
<li>Sterilization: Variable ✓</li>
</ol>
<p><strong>CRITICAL BOTTLENECK:</strong><br>
Thawing limits RP to 163 tons/day</p>
</div><div class="column" style="width:50%;">
<h3 id="pre-cook-chain">Pre-Cook Chain</h3>
<ol type="1">
<li>Sorting: 4,080 t/d ✓</li>
<li>Racking: 252 t/d ⚠️</li>
<li>Pre-cooking: 315 t/d ✓</li>
<li>Cooling: 447 t/d ✓</li>
<li><strong>Cleaning: 251 t/d</strong> ⚠️</li>
<li>Filling: ~16-20 t/d/line ✓</li>
</ol>
<p><strong>CRITICAL BOTTLENECK:</strong><br>
Cleaning tables limit PC to 251 tons/day</p>
</div></div>
</section>
<section id="capacity-utilization-analysis" class="slide level2">
<h2>Capacity Utilization Analysis</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Process</th>
<th>Bottleneck Step</th>
<th>Capacity</th>
<th>Impact</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Raw Pack</strong></td>
<td>Thawing</td>
<td>163 tons/day</td>
<td>Maximum RP throughput</td>
</tr>
<tr class="even">
<td><strong>Pre-Cook</strong></td>
<td>Cleaning</td>
<td>251 tons/day</td>
<td>Maximum PC throughput</td>
</tr>
<tr class="odd">
<td><strong>Combined Theoretical</strong></td>
<td>Both</td>
<td>414 tons/day</td>
<td>If running at max</td>
</tr>
<tr class="even">
<td><strong>Actual Factory</strong></td>
<td>Mixed</td>
<td>335 tons/day</td>
<td>81% utilization</td>
</tr>
</tbody>
</table>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Factory operates below theoretical max—likely due to production scheduling, maintenance, and demand mix</p>
</div>
</div>
</div>
</section>
<section id="recommendations-to-increase-capacity" class="slide level2">
<h2>Recommendations to Increase Capacity</h2>
<h3 id="to-expand-raw-pack-currently-163-td-max">To Expand Raw Pack (Currently 163 t/d max)</h3>
<ol type="1">
<li><strong>Add thawing tanks</strong> - primary constraint</li>
<li>Increase thawing bay capacity</li>
<li>Reduce thaw time through optimization</li>
</ol>
<h3 id="to-expand-pre-cook-currently-251-td-max">To Expand Pre-Cook (Currently 251 t/d max)</h3>
<ol type="1">
<li><strong>Add cleaning tables</strong> - primary constraint</li>
<li><strong>Automate cleaning process</strong> where possible</li>
<li>Improve cleaner productivity (currently 53 kg/hr)</li>
<li>Extend cleaning operating hours beyond 21 hrs/day</li>
</ol>
</section>
<section id="quality-control-food-safety" class="slide level2">
<h2>Quality Control &amp; Food Safety</h2>
<h3 id="critical-control-points-ccps">Critical Control Points (CCPs)</h3>
<p><strong>Throughout Process:</strong> - Temperature monitoring at all stages - Metal detection before packing - Seal integrity testing (vacuum checks) - Retort process validation - Daily quality cuttings</p>
<p><strong>Quality Metrics Checked:</strong> - Vacuum, appearance, smell - Texture, style of pack - Cleanliness, flavor - Fill weight accuracy</p>
</section>
<section id="certifications-standards" class="slide level2">
<h2>Certifications &amp; Standards</h2>
<h3 id="food-safety">Food Safety</h3>
<ul>
<li>HACCP certified</li>
<li>ISO 22000</li>
<li>EU/UK export approval</li>
</ul>
<h3 id="sustainability">Sustainability</h3>
<ul>
<li>Dolphin-safe certification</li>
<li>MSC Chain of Custody</li>
<li>SeaChange® 2030 commitments</li>
</ul>
<h3 id="quality">Quality</h3>
<ul>
<li>Daily sampling and testing</li>
<li>Third-party audits</li>
<li>Customer specifications met</li>
</ul>
</section>
<section id="sustainability-by-products" class="slide level2">
<h2>Sustainability &amp; By-Products</h2>
<h3 id="resource-recovery">Resource Recovery</h3>
<ul>
<li><strong>Heads, frames, guts:</strong> Converted to fishmeal and fish oil</li>
<li><strong>Wastewater:</strong> On-site treatment plant (new $9.9M facility)</li>
<li><strong>Energy:</strong> Solar panels covering 30% of plant (8% of energy needs)</li>
</ul>
<h3 id="seachange-2030-goals">SeaChange® 2030 Goals</h3>
<ul>
<li>Zero water discharge by 2030</li>
<li>Zero waste to landfill by 2030</li>
<li>Zero food loss by 2030</li>
<li>42% GHG emissions reduction by 2030</li>
<li>Net zero by 2050</li>
</ul>
</section>
<section id="environmental-initiatives" class="slide level2">
<h2>Environmental Initiatives</h2>
<ul>
<li><strong>Water recycling systems</strong> operational</li>
<li><strong>Solar energy integration</strong> (30% roof coverage planned)</li>
<li><strong>Sustainable fishing partnerships</strong> (ISSF, SeaBOS member)</li>
<li><strong>Waste minimization programs</strong></li>
<li><strong>Cold storage efficiency improvements</strong></li>
<li><strong>50% female leadership target</strong> (achieved)</li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>IOT ranked #1 in food industry on Dow Jones Sustainability Index 2022</p>
</div>
</div>
</div>
</section>
<section id="complete-process-flow" class="slide level2">
<h2>Complete Process Flow</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">graph LR
    A[Port Victoria - Landing] --&gt; B[Cold Storage 12,000t]
    B --&gt; C{Size Sorting&lt;br/&gt;4,080 t/d}
    
    C --&gt;|Large Fish| RP[Raw Pack Line]:::rp
    C --&gt;|Small Fish| PC[Pre-Cook Line]:::pc
    
    RP --&gt; RP1[Thawing 163t/d&lt;br/&gt;⚠️ BOTTLENECK]:::rpwarn
    RP1 --&gt; RP2[Raw Butchering]:::rp
    RP2 --&gt; RP3[Fill Raw + Liquid&lt;br/&gt;200-350 cpm]:::rp
    RP3 --&gt; RP4[Seaming]:::rp
    RP4 --&gt; RP5[Retort 121°C&lt;br/&gt;41-80 min]:::rp
    RP5 --&gt; Z[Quality Check&lt;br/&gt;Recovery: 62%]
    
    PC --&gt; PC1[Racking 252t/d&lt;br/&gt;245kg/rack]:::pc
    PC1 --&gt; PC2[Pre-Cook 315t/d&lt;br/&gt;4hr @ 90% eff]:::pc
    PC2 --&gt; PC3[Cooling 447t/d&lt;br/&gt;2-3 hours]:::pc
    PC3 --&gt; PC4[Clean 251t/d&lt;br/&gt;⚠️ BOTTLENECK&lt;br/&gt;200 workers]:::pcwarn
    PC4 --&gt; PC5[Fill Cooked&lt;br/&gt;180-500 cpm]:::pc
    PC5 --&gt; PC6[Seaming]:::pc
    PC6 --&gt; PC7[Retort 117°C&lt;br/&gt;47-72 min]:::pc
    PC7 --&gt; Z2[Quality Check&lt;br/&gt;Recovery: 45%]
    
    Z --&gt; Final[Label/Pack/Export&lt;br/&gt;10 Lines @ 83% eff]
    Z2 --&gt; Final
    Final --&gt; Export[Containerization&lt;br/&gt;EU Markets]
    
    RP5 -.-&gt;|By-products| BP[Fishmeal/Oil&lt;br/&gt;+Wastewater Treatment]
    PC4 -.-&gt;|By-products| BP
    
    classDef rp fill:#ffcccc,stroke:#cc0000,stroke-width:3px,color:#000
    classDef pc fill:#cce5ff,stroke:#0066cc,stroke-width:3px,color:#000
    classDef rpwarn fill:#ff9999,stroke:#990000,stroke-width:4px,color:#000
    classDef pcwarn fill:#99ccff,stroke:#003399,stroke-width:4px,color:#000
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="production-statistics" class="slide level2">
<h2>Production Statistics</h2>
<h3 id="daily-capacity-breakdown">Daily Capacity Breakdown</h3>
<ul>
<li><strong>Total Stated Capacity:</strong> 335 tons/day round fish</li>
<li><strong>Theoretical Maximum:</strong> 414 tons/day (if both at max)</li>
<li><strong>Utilization Rate:</strong> 81%</li>
</ul>
<h3 id="possible-production-mix">Possible Production Mix</h3>
<ul>
<li><strong>Scenario 1:</strong> ~140 tons RP + ~195 tons PC</li>
<li><strong>Scenario 2:</strong> Alternating production days</li>
<li><strong>Scenario 3:</strong> Mixed with maintenance windows</li>
</ul>
<h3 id="annual-output">Annual Output</h3>
<ul>
<li><strong>~100,000 tons</strong> processed annually</li>
<li><strong>1.5-2 million cans</strong> produced daily</li>
<li><strong>1,800 employees</strong> across all operations</li>
</ul>
</section>
<section id="economic-impact" class="slide level2">
<h2>Economic Impact</h2>
<h3 id="iots-role-in-seychelles">IOT’s Role in Seychelles</h3>
<ul>
<li><strong>95%</strong> of Seychelles manufacturing exports</li>
<li><strong>88%</strong> of Seychelles’ exports to EU</li>
<li><strong>Largest private employer</strong> (1,800 workers)</li>
<li>Second-largest industry after tourism</li>
<li>Critical during COVID-19 (overtook tourism temporarily)</li>
<li><strong>€50M+</strong> invested in past 5 years</li>
<li>Additional <strong>€10M</strong> investment planned</li>
</ul>
</section>
<section id="ownership-brands" class="slide level2">
<h2>Ownership &amp; Brands</h2>
<h3 id="ownership-structure">Ownership Structure</h3>
<ul>
<li><strong>Thai Union Group:</strong> 60% (Thai Union Europe subsidiary)</li>
<li><strong>Seychelles Government:</strong> 40% (via SSI)</li>
</ul>
<h3 id="product-brands">Product Brands</h3>
<ul>
<li><strong>Petit Navire</strong> (France)</li>
<li><strong>John West</strong> (UK)</li>
<li><strong>Mareblu</strong> (Europe)</li>
<li>Various private label brands</li>
</ul>
</section>
<section id="summary---key-takeaways" class="slide level2">
<h2>Summary - Key Takeaways</h2>
<ol type="1">
<li><strong>Two distinct methods:</strong> Raw Pack (62% recovery) vs Pre-Cook (45% recovery)</li>
<li><strong>Raw Pack:</strong> Single cooking, juicier, faster—bottlenecked by thawing (163 t/d)</li>
<li><strong>Pre-Cook:</strong> Double cooking, cleaner taste—bottlenecked by cleaning (251 t/d)</li>
<li><strong>Factory operates at 335 t/d</strong> (81% of theoretical 414 t/d capacity)</li>
<li><strong>1.5-2 million cans/day</strong> serving major European brands</li>
<li><strong>Strong sustainability focus</strong> with SeaChange® 2030 commitments</li>
<li><strong>Critical economic contributor</strong> to Seychelles economy</li>
</ol>
</section>
<section id="future-opportunities" class="slide level2">
<h2>Future Opportunities</h2>
<h3 id="capacity-expansion">Capacity Expansion</h3>
<ul>
<li>Add thawing capacity for Raw Pack</li>
<li>Automate or expand cleaning for Pre-Cook</li>
<li>Optimize production scheduling</li>
</ul>
<h3 id="sustainability-1">Sustainability</h3>
<ul>
<li>Complete solar panel installation</li>
<li>Achieve zero waste goals by 2030</li>
<li>Carbon neutrality by 2050</li>
</ul>
<h3 id="market-development">Market Development</h3>
<ul>
<li>New product formats</li>
<li>Additional export markets</li>
<li>Value-added products</li>
</ul>
</section>
<section id="thank-you" class="slide level2">
<h2>Thank You</h2>
<h3 id="questions">Questions?</h3>
<p><strong>Indian Ocean Tuna Limited</strong><br>
Fishing Port, Victoria, Mahé, Seychelles<br>
Tel: +248 4282500</p>
<p><strong>Parent Company:</strong> Thai Union Group PCL<br>
Website: www.thaiunion.com</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Part of Thai Union’s global network - World’s leading seafood company</p>
</div>
</div>
</div>
</section>
<section class="slide level2">


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="logo-getgain.png" class="slide-logo"></p>
<div class="footer footer-default">
<p>GETGAIN SOLUTIONS</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="iot_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="iot_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="iot_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="iot_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="iot_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="iot_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="iot_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="iot_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="iot_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="iot_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1920,

        height: 1080,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>